In [3]:
!pip install numpy 


[notice] A new release of pip is available: 24.1 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [4]:
import numpy as np

### Creating Arrays

In [7]:
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
np.zeros( (3, 4) ) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones( (3, 4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#To create a 3 by 4 array with the value 5
np.full( (3, 4), 5 )

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [12]:
#To create an array of 10 numbers from 0 to 9, i.e. [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#To create an array of odd numbers from 1 to 10, i.e. [1, 3, 5, 7, 9]
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [14]:
#To create an array with 3 evenly spaced numbers between 0 to 9
np.linspace(0, 9, 3)

array([0. , 4.5, 9. ])

### Attributes of ndarray

In [53]:
#ndarray.ndim – the number of axes (dimensions) of the array.
#ndarray.shape – the dimensions of the array.
#ndarray.size – the number of elements.
#ndarray.dtype – the data type object of the array, which gives details on the type and size of the data.
#ndarray.dtype.name -- the name of the data type.
#ndarray.dtype.name – the type of the elements in the array
print(a)
print(a.ndim)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.dtype.name)
print(b)
print(b.ndim)
print(b.size)
print(b.shape)
print(b.dtype)
print(b.dtype.name)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
2
12
(3, 4)
int64
int64
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
2
12
(3, 4)
int64
int64


### Changing the Shape of the Array

In [27]:
#reshape() – return an array with the modified shape
#resize() – modify the array shape
#ravel() – return a flattened array
a = np.array([[0,1,2,3],[4,5,6,7]])
a.reshape(4,2)
print("a =",a)
a.resize(4,2)
print("a =",a)
c = a.ravel()
print("c =",c)


a = [[0 1 2 3]
 [4 5 6 7]]
a = [[0 1]
 [2 3]
 [4 5]
 [6 7]]
c = [0 1 2 3 4 5 6 7]


### Printing Arrays

In [29]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [30]:
print(np.arange(10000).reshape(500,20))

[[   0    1    2 ...   17   18   19]
 [  20   21   22 ...   37   38   39]
 [  40   41   42 ...   57   58   59]
 ...
 [9940 9941 9942 ... 9957 9958 9959]
 [9960 9961 9962 ... 9977 9978 9979]
 [9980 9981 9982 ... 9997 9998 9999]]


### Transposing the Array

In [36]:
# transpose() – reverse or permute the axes of an array and return that modified array (Note: same as ndarray.transpose())
# flip() – reverse the order of elements in an array along the given axis. If axis not specified, flip over all axes.

a = np.array([[0,1,2,3],[4,5,6,7]])
t1 = a.transpose()
print(t1)
t2 = a.transpose((1,0))
print(t2)
f = np.flip(a)
print(f)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[7 6 5 4]
 [3 2 1 0]]


In [33]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

print (a * b) # Return elementwise product
print (a @ b) # Return matrix product
print (a.dot(b)) # Return matrix product

[[1 0]
 [0 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Indexing and Slicing

In [5]:
# Indexing and slicing on one-dimensional array
a = np.arange(0, 8, 2)
print (a)
print (a[2]) # Indexing
print (a[1:3]) # Slicing

[0 2 4 6]
4
[2 4]


In [1]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
b = a[:2] # b is a new array object: [[0,1,2],[3,4,5]]
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is also modified

NameError: name 'np' is not defined

Indexing with Boolean Array

In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a>0)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a[ a<5 ])
print (a[ a%2 == 0 ])

[0 1 2 3 4]
[0 2 4 6 8]


Indexing with Array of Indices

In [ ]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
i = np.array([[0,2], [0, 1]])
print (a[i])

[[[0 1 2]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]]]


### Operations

In [40]:
a = np.arange(12).reshape(3,4)
print(a)
print(a * 10)
print(a < 5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [41]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[1, 2], [3, 4]])

print (a * b) # Return elementwise product
print (a @ b) # Return matrix product
print (a.dot(b)) # Return matrix product

[[1 0]
 [0 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


### Indexing and Slicing

In [42]:
# Indexing and slicing on one-dimensional array
a = np.arange(0, 8, 2)
print (a)
print (a[2]) # Indexing
print (a[1:3]) # Slicing

[0 2 4 6]
4
[2 4]


In [45]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print(a)
b = a[:2] # b is a new array object: [[0,1,2],[3,4,5]]
print(b)
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is also modified

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]]
[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


In [52]:
b = np.arange(0,24,2).reshape(3, 4) 
print(b)
print(b[1,2])
print(b[0:2,1])
print(b[:,1])

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
12
[ 2 10]
[ 2 10 18]


### Iterating Array

In [54]:
b = np.arange(0, 24, 2).reshape(3, 4)
for row in b:
    print (row)

[0 2 4 6]
[ 8 10 12 14]
[16 18 20 22]


In [55]:
for x in b.flat:
    print (x)

0
2
4
6
8
10
12
14
16
18
20
22


### Copying

In [56]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
print (a)

b = a # b is a reference of a, not a new array object
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is modified 

[[0 1 2]
 [3 4 5]]
[[  0   1 100]
 [  3   4   5]]


In [57]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
b = a.copy() # b is a new array object

b[0, 2] = 100 # Modifying one of b's elements
print (a) # Only b is modified, but not a

[[0 1 2]
 [3 4 5]]


In [58]:
a = np.arange(6).reshape(2, 3) # [[0,1,2],[3,4,5]]
b = a.view() # b is a new array object

b[0, 2] = 100 # Modifying one of b's elements
b.resize(3, 2) # b's shape is changed
print (a) # a's data is changed but shape is not changed

[[  0   1 100]
 [  3   4   5]]


In [59]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
b = a[:2] # b is a new array object: [[0,1,2],[3,4,5]]
b[0, 2] = 100 # Modifying one of b's elements
print (a) # a is also modified

[[  0   1 100]
 [  3   4   5]
 [  6   7   8]]


### Indexing with Boolean Array

In [61]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a>0)

[[False  True  True]
 [ True  True  True]
 [ True  True  True]]


In [62]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
print (a[ a<5 ])
print (a[ a%2 == 0 ])

[0 1 2 3 4]
[0 2 4 6 8]


### Indexing with Array of Indices


In [63]:
a = np.arange(9).reshape(3, 3) # [[0,1,2],[3,4,5],[6,7,8]]
i = np.array([[0,2], [0, 1]])
print (a[i])

[[[0 1 2]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]]]


### Data Types

In [65]:
x = np.double(1)
print (x)

1.0


In [ ]:
y = np.intc([0.5, 1.5, 2.5])
print (y)

[0 1 2]


In [ ]:
z = np.arange(5, dtype=np.double)
print (z)

[0. 1. 2. 3. 4.]


In [ ]:
w = np.array([0.5, 1.5, 2.5], dtype=np.single)
print (w)

[0.5 1.5 2.5]


In [ ]:
a = w.astype(int) # Return a copy of the array casted to the given type
print (a)

[0 1 2]
